IF
	InParty("Valen")
	Global("D0ValenIn","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("D0ValenIn","GLOBAL",1)
		ReputationInc(-4)
		IncrementGlobal("D0Change","GLOBAL",-4)
END

IF
	!InParty("Valen")
	Global("D0ValenIn","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("D0ValenIn","GLOBAL",2)
		ReputationInc(2)
END

IF
	InParty("Valen")
	Global("D0ValenIn","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("D0ValenIn","GLOBAL",1)
		ReputationInc(-2)
END
