IF
	InParty("Jaheira")
	G("FWJaheiraEvilCheckOne",0)
	Alignment(Player1,MASK_EVIL)
	GlobalLT("D0Happiness","LOCALS",10)
THEN
	RESPONSE #100
		SG("FWJaheiraEvilCheckOne",1)
		SG("FWJaheiraEvilEp",1)
END

IF
	InParty("Jaheira")
	G("FWJaheiraEvilCheckTwo",0)
	!Alignment(Player1,MASK_EVIL)
	GlobalLT("D0Happiness","LOCALS",7)
THEN
	RESPONSE #100
		SG("FWJaheiraEvilCheckTwo",1)
		SG("FWJaheiraEvilEp",1)
END


