IF
	True()
THEN
	RESPONSE #100
		CutSceneId("tolger")
		Wait(1)
		ForceSpell("Valygar",FLASHY_1)
		ActionOverride("Valygar",LeaveParty())
		Wait(2)
		Wait(1)
		ActionOverride("Valygar",DropInventory())
		ActionOverride("Valygar",DestroySelf())
		IncrementGlobal("D0Change","GLOBAL",-2)
		SetGlobal("SPRITE_IS_DEADValygar","GLOBAL",1)
		SetGlobal("ValygarGone","GLOBAL",1)
		StartDialogueNoSet(Player1)
END

